#!/bin/sh

# Gradle start up script for POSIX generated by Gradle.
# Simplified wrapper bootstrap: downloads and launches the Gradle distribution.

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

GRADLE_USER_HOME="${GRADLE_USER_HOME:-$HOME/.gradle}"

WRAPPER_PROPERTIES="$(dirname "$0")/gradle/wrapper/gradle-wrapper.properties"
DISTRIBUTION_URL=$(grep '^distributionUrl=' "$WRAPPER_PROPERTIES" | cut -d'=' -f2- | sed 's/\\:/:/g')
DIST_NAME=$(basename "$DISTRIBUTION_URL" .zip)
DIST_DIR="$GRADLE_USER_HOME/wrapper/dists/$DIST_NAME"

if [ ! -d "$DIST_DIR" ]; then
  echo "Downloading $DISTRIBUTION_URL ..."
  mkdir -p "$DIST_DIR"
  TMP_ZIP="$DIST_DIR/gradle.zip"
  if command -v curl >/dev/null 2>&1; then
    curl -fSL -o "$TMP_ZIP" "$DISTRIBUTION_URL"
  elif command -v wget >/dev/null 2>&1; then
    wget -O "$TMP_ZIP" "$DISTRIBUTION_URL"
  else
    echo "Need curl or wget to download the Gradle distribution." >&2
    exit 1
  fi
  UNPACK_DIR="$DIST_DIR/unpacked"
  mkdir -p "$UNPACK_DIR"
  if command -v unzip >/dev/null 2>&1; then
    unzip -q -o "$TMP_ZIP" -d "$UNPACK_DIR"
  else
    echo "Need unzip to unpack the Gradle distribution." >&2
    exit 1
  fi
fi

GRADLE_HOME=$(find "$DIST_DIR/unpacked" -maxdepth 1 -name "gradle-*" -type d | head -n 1)
if [ -z "$GRADLE_HOME" ]; then
  echo "Could not locate unpacked Gradle distribution in $DIST_DIR" >&2
  exit 1
fi

JAVACMD="${JAVA_HOME:+$JAVA_HOME/bin/java}"
if [ -z "$JAVACMD" ]; then
  JAVACMD="java"
fi

exec "$JAVACMD" \
  -Dorg.gradle.appname="$APP_BASE_NAME" \
  -classpath "$GRADLE_HOME/lib/gradle-launcher-"*.jar \
  org.gradle.launcher.GradleMain "$@"
